[project]
name = "dotnvim"
version = "0.1"
description = "neovim's config files"
readme = "README.md"
authors = [{ name = "mike325", email = "mike325@users.noreply.github.com" }]
license = { text = "MIT" }
# dependencies = [
#     'httpie',
#     'debugpy',
#     'black[d]',
#     'jedi',
#     'mypy',
#     'flake8',
#     'flake8-mypy',
#     'yapf',
#     'mccabe',
# ]

# # NOTE: flake8 does not support pyproject use .flake8 config
# [tool.flake8]
# max-complexity = 20
# max-line-length = 120
# ignore =
#     # E121,
#     # E123,
#     # E126,
#     # Whitespace before :
#     E203,
#     # E221,
#     # Whitespace around operators
#     E226,
#     # E228,
#     # Missing whitespace after ,
#     E231,
#     # E24,
#     # E251,
#     # 2 spaces before inline comment
#     E261,
#     # Comments should start with #
#     E262,
#     # Block comment should start with #
#     E265,
#     # E27,
#     # Expected 2 lines between funcs/classes
#     E302,
#     # E501,
#     # E701,
#     # E704,
#     # H233,
#     # Blank line and the EOF
#     W391,
#     # W503,
#     # W504,
# exclude =
#     # No need to traverse our git directory
#     .git,
#     # There's no value in checking cache directories
#     __pycache__,
#     # The conf file is mostly autogenerated, ignore it
#     build,
#     # This contains builds of flake8 that we don't want to check
#     dist
# per-file-ignores =
#     # imported but unused
#     __init__.py: F401

[tool.black]
line-length = 120
target-version = ['py37']
# include = '\.pyi?$'
exclude = '''
    (
    /(
        \.eggs       # exclude a few common directories in the
        | \.git          # root of the project
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | dist
    )/
    )
'''

[tool.mypy]
python_version = "3.7"
# sqlite_cache = true
# check_untyped_defs = true
# disallow_any_generics = true
# disallow_incomplete_defs = true
# disallow_untyped_defs = true
ignore_missing_imports = true
warn_redundant_casts = true
warn_unreachable = true
warn_return_any = true
warn_unused_ignores = true
no_implicit_optional = true
# follow_imports = "silent"  # {normal,silent,skip,error}

# mypy per-module options:
# [[tool.mypy.overrides]]
# module = "mycode.foo.*"
# disallow_untyped_defs = true
