-- function! plugins#neomake#makeprg() abort
--     if empty(&makeprg)
--         return
--     endif
--     local ft = &filetype
--     local makeprg = map(split(&makeprg, ' '), {key, val -> substitute(val, '^%$', '%t', 'g') })
--     local executable = l:makeprg[0]
--     local args = l:makeprg[1:]
--     local name = plugins#convert_name(l:executable)

--     let b:neomake_{l:ft}_enabled_makers = [l:name]
--     let b:neomake_{l:ft}_{l:name}_maker = {
--         \   'exe': l:executable,
--         \   'args': l:args,
--         \   'errorformat': !empty(&l:errorformat) ? &l:errorformat : &errorformat,
--         \}
-- endfunction

-- augroup NeomakeConfig
--     autocmd!
--     autocmd OptionSet makeprg call plugins#neomake#makeprg()
-- augroup end
