name: lint

on: [push, pull_request]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: OS Info
        run: |
          sudo apt-get update
          sudo apt-get install wget
          mkdir -p ~/.local/bin/
          wget -O ~/.local/bin/screenfetch https://git.io/vaHfR
          chmod +x ~/.local/bin/screenfetch
          ~/.local/bin/screenfetch
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            bison              \
            curl               \
            git                \
            shellcheck         \
            python3-setuptools \
            python-setuptools  \
            python3-pip        \
            python3-virtualenv \
            luarocks           \
            golang

          sudo luarocks install luacheck
          # FIX: Temporally fix as currently the latest tag does not have a release
          rm -f ~/.local/bin/shfmt
          bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
          source /home/mike/.gvm/scripts/gvm
          gvm install go1.18.3 -B
          gvm use go1.18.3 --default
          go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - name: Fetch install script
        run: |
          wget https://raw.githubusercontent.com/Mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
          ./install.sh --portables --verbose
      - uses: pre-commit/action@v2.0.3
