name: lint

on: [push, pull_request]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: OS Info
        run: |
          sudo apt-get install wget
          wget -O screenfetch-dev https://git.io/vaHfR
          chmod +x screenfetch-dev
          ./screenfetch-dev
      - name: Install dependencies
        run: |
          sudo apt-get install -y curl git python3-setuptools python-setuptools luarocks python3-pip python3-virtualenv
          sudo luarocks install luacheck
          WORK_DIR="$HOME/.local/share"
          mkdir -p "$WORK_DIR" && pushd "$WORK_DIR"
          virtualenv -p python3 vint
          source ./vint/bin/activate
          pip install vim-vint
          sudo ln -s "${VIRTUAL_ENV}/bin/vint" /usr/bin/
          deactivate
          popd
      - name: Fetch install script
        run: |
          wget https://raw.githubusercontent.com/Mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
          ./install.sh --portables --verbose --force
      - uses: pre-commit/action@v2.0.3
