name: lint

on: [push, pull_request]

# env:
#   GO_VERSION: go1.18.3

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: OS Info
        run: |
          sudo apt update
          sudo apt install wget
          mkdir -p ~/.local/bin/
          wget https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch && chmod +x ./neofetch && ./neofetch
      - name: Install dependencies
        run: |
          sudo apt install -y      \
                bison              \
                curl               \
                git                \
                shellcheck         \
                python3-setuptools \
                python3-pip        \
                python3-virtualenv \
                luarocks           \
                golang

          sudo luarocks install luacheck

          # FIX: Temporally fix as currently the latest tag does not have a release
          # rm -f ~/.local/bin/shfmt
          # bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
          # source "$HOME/.gvm/scripts/gvm"
          # gvm install "$GO_VERSION" -B
          # gvm use "$GO_VERSION" --default
          # go install mvdan.cc/sh/v3/cmd/shfmt@latest

          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/go/bin/" >> $GITHUB_PATH

      - name: Fetch install script
        run: |
          wget https://raw.githubusercontent.com/mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
          ./install.sh --nolog --portables --verbose
      - uses: pre-commit/action@v3.0.1
