name: lint

on: [push, pull_request]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Cache precommit virutalenvs
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pre-commit/
            ~/.cache/pip/
          key: ${{runner.os}}-pre-commit-${{hashFiles('.pre-commit-config.yaml')}}
      - name: OS Info
        run: |
          sudo apt-get install wget
          mkdir -p ~/.local/bin/
          wget -O ~/.local/bin/screenfetch https://git.io/vaHfR
          chmod +x ~/.local/bin/screenfetch
          ~/.local/bin/screenfetch
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            curl               \
            git                \
            shellcheck         \
            python3-setuptools \
            python-setuptools  \
            python3-pip        \
            python3-virtualenv \
            luarocks           \
            golang

          sudo luarocks install luacheck
      - name: Fetch install script
        run: |
          wget https://raw.githubusercontent.com/Mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
          ./install.sh --portables --verbose --force
      - uses: pre-commit/action@v2.0.3
