name: macos-stable
on: [push, pull_request]

jobs:
  osx-build:
    name: Testing install script in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macOS-latest, macos-11, macos-10.15 ]

    env:
      GITHUB: true

    steps:
      - uses: actions/checkout@v2
      - name: OS Info
        run: |
          brew install shellcheck
          brew install neovim
          wget -O screenfetch-dev https://git.io/vaHfR
          chmod +x screenfetch-dev
          ./screenfetch-dev
      - name: Fetch script
        run: |
          curl -OL https://raw.githubusercontent.com/Mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
      - name: Install dotfiles and dependencies
        run: |
          ./install.sh --verbose --neovim --python=3
      - name: Test stable neovim
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          make
