name: neovimfiles

on: [push, pull_request]

jobs:
  linux-build:
    name: Testing install script in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-20.04, ubuntu-18.04 ]

    env:
      GITHUB: true

    steps:
      - uses: actions/checkout@v2
      - name: OS Info
        run: |
          sudo apt-get install -y wget
          wget -O screenfetch-dev https://git.io/vaHfR
          chmod +x screenfetch-dev
          ./screenfetch-dev
      - name: Install system packages
        run: |
          sudo apt-get install -y curl git shellcheck python3-setuptools python-setuptools build-essential cmake python3-dev python3-pip
      - name: Fetch script
        run: |
          curl -OL https://raw.githubusercontent.com/Mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
      - name: Install dotfiles and dependencies
        run: |
          ./install.sh --verbose --vim --nvim --python=3 --portables
          sudo pip3 install --upgrade pip python-language-server
      - name: Test neovim and stock vim
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./test/test.sh
      - name: Test latest vim
        run: |
          sudo apt-get install -y vim
          export PATH="$HOME/.local/bin:$PATH"
          ./test/test.sh --vim
      - name: Test latest neovim
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./install.sh --neovim dev --force
          ./test/test.sh --nvim

  osx-build:
    name: Testing install script in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macOS-latest ]

    env:
      GITHUB: true

    steps:
      - uses: actions/checkout@v1
      - name: OS Info
        run: |
          brew install git shellcheck neovim cmake wget python
          wget -O screenfetch-dev https://git.io/vaHfR
          chmod +x screenfetch-dev
          ./screenfetch-dev
      - name: Fetch script
        run: |
          curl -OL https://raw.githubusercontent.com/Mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
      - name: Install dotfiles and dependencies
        run: |
          ./install.sh --verbose --vim --neovim=dotfiles --python=3
          pip3 install --upgrade python-language-server
      - name: Test neovim and stock vim
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./test/test.sh
      - name: Install new vim
        run: |
          brew install vim
      - name: Test latest vim
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./test/test.sh --vim

  windows-build:
    name: Testing install script in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest, windows-2019, windows-2016 ]

    env:
      GITHUB: true

    steps:
      - uses: actions/checkout@v1
      - name: Enable Chocolatey
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - name: Install system packages
        shell: powershell
        run: |
          choco install -y python git curl vim neovim mingw cmake
      - name: Fetch script
        shell: bash
        run: |
          curl -OL https://raw.githubusercontent.com/Mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
      - name: Install dotfiles and dependencies
        shell: bash
        run: |
          ./install.sh --verbose --vim --neovim=dotfiles --python=3 --portables
      - name: Basic stock test
        shell: bash
        run: |
          export PATH="/c/tools/neovim/Neovim/bin:$PATH"
          ./test/test.sh
